# Generated by Django 6.0.3 on 2026-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='queue_order',
            field=models.IntegerField(default=0),
        ),
    ]
